services:
  app:
    # image: events-monitor
    container_name: events_monitor
    build: .
    environment:
      - TZ=Asia/Yekaterinburg
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ["node", "--inspect=0.0.0.0:9229", "main.js"]